### ISSUE TITLE
Comment faire tourner en production ?

### ISSUE THREAD

**Issue by alexsegura** [Mainstenant/allons-y#1]
Salut @XavierBoubert je vais héberger le wiki d'ici peu.

J'ai tout dumpé et ça marche en faisant `npm run start`, mais je ne vois pas comment le lancer en arrière plan ?

Est-il possible de le faire tourner avec un truc comme PM2 ou Supervisor ?
J'ai essayé mais j'obtiens cette erreur, je ne comprends pas pourquoi : 

```
TypeError: Cannot read property 'substring' of undefined
   at Interface._getCursorPos (readline.js:642:49)
   at Interface._refreshLine (readline.js:271:24)
   at _this.output (/var/www/mainstenant-wiki/node_modules/allons-y/features/allons-y/allons-y-live-commands.js:187:10)
   at outputBanner (/var/www/mainstenant-wiki/node_modules/allons-y/features/allons-y/allons-y-logs.js:86:11)
   at start (/var/www/mainstenant-wiki/node_modules/allons-y/features/allons-y/allons-y-processes.js:391:11)
   at /var/www/mainstenant-wiki/node_modules/allons-y/features/allons-y/allons-y-processes.js:385:15
   at /var/www/mainstenant-wiki/node_modules/allons-y/features/allons-y/allons-y-processes.js:518:9
   at /var/www/mainstenant-wiki/node_modules/allons-y/features/allons-y/allons-y-bootstrap.js:63:7
   at /var/www/mainstenant-wiki/node_modules/allons-y/node_modules/async/dist/async.js:486:20
   at /var/www/mainstenant-wiki/node_modules/allons-y/node_modules/async/dist/async.js:1074
```

**Comment by XavierBoubert** [comment]
Hello. Tu peux utiliser une session "screen" ou dockeriser ton app. Je n'ai jamais testé sur PM2 ni Supervisor.

**Comment by alexsegura** [comment]
Ok Docker faut voir. Je ne maîtrise pas trop, mon instance de MongoDB est sur un autre serveur, est-ce que je pourrai atteindre la machine ?

J'ai l'impression que l'erreur apparaît quand il n'y a pas de sortie standard ou un truc comme ça.

**Comment by XavierBoubert** [comment]
Essaie de desactiver la Live command avec "node allons-y env"

Si tu peux pinger ton serveur mongodb de ta machine oui tu pourra t'y connecter.

**Comment by taniki** [comment]
J'ai retenté de lancer le wiki en utilisant pm2. Il s'avère que la variable dans `.env` qui permet de désactiver le live prompt, ne le désactive pas. ça change surtout l'affichage de la progression du lancement
